version: '3.3'
services:
  pozos-registry:
    image: registry:2.8.1
    container_name: pozos-registry
    restart: always
    ports: 
      - "5050:5000"
    volumes:
      - ${PWD}/data/registry:/var/lib/registry
      - ./registry/auth:/auth
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_AUTH=htpasswd
      - "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    command:
      - /bin/sh
      - -c
      - 'apk add --no-cache apache2-utils && htpasswd -Bbn pozos pozos-registry > /auth/htpasswd && registry serve /etc/docker/registry/config.yml'
    networks:
      - pozos_registry_network

  frontend_registry:
    image: joxit/docker-registry-ui:2
    container_name: frontend_registry
    depends_on:
      - pozos-registry
    ports: 
      - "8080:80"
    environment:
      - NGINX_PROXY_PASS_URL=http://pozos-registry:5050
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=Pozos
      - SINGLE_REGISTRY=true
    networks:
      - pozos_registry_network

networks:
  pozos_registry_network:
